BrainSync/BrainSyncSite/Controllers/HealthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrainSyncSite.Controllers
{
    public class HealthController : Controller
    {
        // GET: Health
        public ActionResult Index()
        {
            ViewBag.Message = "健康是一切開始的前提！";
            return View();
        }
    }
}

BrainSync/BrainSyncSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrainSyncSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

      
    }
}

BrainSync/BrainSyncSite/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrainSyncSite.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            ViewBag.Message = "最近發生的事情";

            return View();
        }
        //这里规划为一个论坛、在线编辑器、页面通讯
        public ActionResult News()
        {
            

            return View();
        }
    }
}

BrainSync/BrainSyncSite/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrainSyncSite.Note.Controllers
{
    public class NoteController : Controller
    {
        // GET: Note
        public ActionResult Index()
        {
            ViewBag.Message = "今天的狀態會影響明天的自己。全力以赴！";

            return View();
        }
    }
}

BrainSync/BrainSyncSite/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrainSyncSite.Controllers
{
    public class SupportController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            ViewBag.Message = "点击客服，可以与我们实时通讯。";
            ViewBag.Head = "提供全方位的技術支持是我們的習慣。";
            return View();
        }
    }
}

BrainSync/BrainSyncSite/Views/Health/Index.cshtml
@{
    ViewBag.Title = "健康";
}
<h2>@ViewBag.Message</h2>
@*<h3>@ViewBag.Message</h3>*@

<p draggable="true">下一步要把智能手環的數據存入數據庫，並在這裡加載顯示出來。</p>
<div>Git我用的很不熟悉，废了老大劲；今晚在家写的希望明天到公司后可以从Github更新下来。</div>

<script>
    alert("Start here and now!");
</script>

BrainSync/BrainSyncSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "脑同步";
}

<div class="jumbotron">
    <h1>編程之路</h1>
    <p class="lead">每天都要有所進步，才能開啟更好的人生</p>
    <p><a href="/News/Index" class="btn btn-primary btn-lg">了解更多 &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>語言</h2>
        <p>
           C#是當務之急
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">了解更多 &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>內核</h2>
        <p>Windows深入是必須的基礎</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">了解更多 &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>網絡</h2>
        <p>這個是長久的鑽研內容</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">了解更多 &raquo;</a></p>
    </div>
</div>

BrainSync/BrainSyncSite/Views/News/Index.cshtml
@{
    ViewBag.Title = "社區";
}
<script src="/Scripts/echarts.js"></script>

<h2>@ViewBag.Message.</h2>
@*<h3>@ViewBag.Message</h3>*@

<p>盡快實現一個論壇，並能夠基於網頁的通訊和在線編輯工具。</p>

<div id="main" style="width: 600px;height:400px;"></div>

<script type="text/javascript">

    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));

    var data = [];

    for (var i = 0; i <= 360; i++) {
        var t = i / 180 * Math.PI;
        var r = Math.sin(2 * t) * Math.cos(2 * t);
        data.push([r, i]);
    }

    option = {
        title: {
            text: '极坐标双数值轴'
        },
        legend: {
            data: ['line']
        },
        polar: {
            center: ['50%', '54%']
        },
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross'
            }
        },
        angleAxis: {
            type: 'value',
            startAngle: 0
        },
        radiusAxis: {
            min: 0
        },
        series: [{
            coordinateSystem: 'polar',
            name: 'line',
            type: 'line',
            showSymbol: false,
            data: data
        }],
        animationDuration: 2000
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>

BrainSync/BrainSyncSite/Views/Note/Index.cshtml
@{
    ViewBag.Title = "日誌";
}

<h2>@ViewBag.Message</h2>

<p style="">@DateTime.Now</p>
<p contenteditable="true" contextmenu="abc,edf">記錄好每天的收穫。</p>
<div>这段文字编辑于笔记本，我要提交到Git；以方便到家后，接着继续编辑。</div>

<h3 onclick="toggleHidden()">处理器架构</h3>
<p>2018-08-31</p>
<div id="toggle">
    RISC 和CISC 是目前设计制造微处理器的两种典型技术，虽然它们都是试图在体系结构、操作运行、软件硬件、编译时间和运行时间等诸多因素中做出某种平衡，以求达到高效
的目的，但采用的方法不同，因此，在很多方面差异很大，它们主要有：
    <ol>
        <li>
            指令系统：RISC 设计者把主要精力放在那些经常使用的指令上，尽量使它们具有简单高效的特色。对不常用的功能，常通过组合指令来完成。因此，在RISC 机器上实现特殊功能时，效率可能较低。但可以利用流水技术和超标量技术加以改进和弥补。而CISC 计算机的指令系统比较丰富，有专用指令来完成特定的功能。因此，处理特殊任务效率较高。
        </li>
        <li>
            存储器操作：RISC 对存储器操作有限制，使控制简单化；而CISC 机器的存储器操作指令多，操作直接。
        </li>
        <li>
            程序：RISC 汇编语言程序一般需要较大的内存空间，实现特殊功能时程序复杂，不易设计；而CISC 汇编语言程序编程相对简单，科学计算及复杂操作的程序社设计相对容易，效率较高。
        </li>
        <li>
            中断：RISC 机器在一条指令执行的适当地方可以响应中断；而CISC 机器是在一条指令执行结束后响应中断。
        </li>
        <li>
            CPU：RISC CPU 包含有较少的单元电路，因而面积小、功耗低；而CISC CPU 包含有丰富的电路单元，因而功能强、面积大、功耗大。
        </li>
        <li>
            设计周期：RISC 微处理器结构简单，布局紧凑，设计周期短，且易于采用最新技术；CISC 微处理器结构复杂，设计周期长。
        </li>
        <li>
            用户使用：RISC 微处理器结构简单，指令规整，性能容易把握，易学易用；CISC微处理器结构复杂，功能强大，实现特殊功能容易。
        </li>
        <li>
            应用范围：由于RISC 指令系统的确定与特定的应用领域有关，故RISC 机器更适合于专用机；而CISC 机器则更适合于通用机。
        </li>
    </ol>
</div>

<table>
    <tr>
        <td>age</td>
        <td>name</td>
        <td>sex</td>
    </tr>
    <tr>
        <td>b</td>
        <td>Jim</td>
        <td>Man</td>
    </tr>
    <tr>
        <td>c</td>
        <td>Ross</td>
        <td>Women</td>
    </tr>
</table>
<script type="text/javascript">
    //折叠文章片段
    var toggleHidden = function () {
        var elem = document.getElementById("toggle");
        if (elem.hasAttribute("hidden")) {
            elem.removeAttribute("hidden");
        } else {
            elem.setAttribute("hidden", "hidden");
        }
    }
</script>

BrainSync/BrainSyncSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 生活所在</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("腦同步", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("主頁", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("社區", "Index", "News")</li>
                    <li>@Html.ActionLink("技術支持", "Index", "Support")</li>
                    <li>@Html.ActionLink("健康", "Index", "Health")</li>
                    <li>@Html.ActionLink("日誌", "Index", "Note")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="">&copy; @DateTime.Now.Year - 版权所有</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BrainSync/BrainSyncSite/Views/Support/Contact.cshtml
@{
    ViewBag.Title = "联系我们";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    科学大道，高新区<br />
    河南省郑州市<br />
    <abbr title="Phone">P:</abbr>
    888 888 66
</address>

<address>
    <strong>支持:</strong> <a href="mailto:techcenter@sina.cn">techcenter@sina.cn</a><br />
    <strong>商务:</strong> <a href="mailto:sysnlee@hotmail.com">sysnlee@hotmail.com</a>
</address>

BrainSync/BrainSyncSite/Views/Support/Index.cshtml
<!DOCTYPE HTML>
<h2>@ViewBag.Head</h2>
<h3>@ViewBag.Message</h3>

<html>
@{
    ViewBag.Title = "技術支持";
}
<head>
    <script>
        var toggleHidden = function () {
            var elem = document.getElementById("toggle");
            if (elem.hasAttribute("hidden")) {
                elem.removeAttribute("hidden");
            } else {
                elem.setAttribute("hidden", "hidden");
            }
        }
    </script>
</head>
<body>
    <button onclick="toggleHidden()" title="切换客服">切换客服</button>
    <table>
        <tr>
            <th>Name</th>
            <th>City</th>
        </tr>
        <tr>
            <td>Adam Freeman  </td>
            <td>London</td>
        </tr>
        <tr id="toggle" >
            <td>Joe Smith</td>
            <td>New York</td>
        </tr>
        <tr>
            <td>Anne Jone</td>
            <td>Paris</td>
        </tr>
    </table>
    <br />
    <address>
        科学大道，高新区<br />
        河南省郑州市<br />
        <abbr title="Phone">P:</abbr>
        888 888 66
    </address>

    <address>
        <strong>支持:</strong> <a href="mailto:techcenter@sina.cn">techcenter@sina.cn</a><br />
        <strong>商务:</strong> <a href="mailto:sysnlee@hotmail.com">sysnlee@hotmail.com</a>
    </address>
</body>
</html>